### ISSUE TITLE
I would like to join your team and contribute with my many years of experience and skills.

### ISSUE THREAD

**Issue by johnsmith0212** [thanhhoajs/websocket#8]
Hi, I'm Ethan Tan, a seasoned web full-stack and blockchain developer with over 8 years of experience in the industry. I specialize in building robust, scalable web applications and innovative blockchain solutions. Leveraging my expertise in frameworks like React.js, Vue.js, and Next.js, along with my proficiency in Solidity for smart contract development, I deliver high-quality, secure, and efficient solutions tailored to meet your specific needs.

**Comment by nguyennhukhanh** [comment]
Hello, we're glad you learned about our project. Currently this project is open source, anyone can contribute and develop it better! We are a non-profit organization, so if you want to pay to contribute to this project, that is not possible!
Best regards!

**Comment by johnsmith0212** [comment]
okay
If you need dev, plz contact
